version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: express_app
    restart: unless-stopped
    ports: 
      - "8080:8080"
    volumes:
      - .:/home/node/app
